project:
  type: book
  output-dir: docs

extensions: [quarto-ext/panel]

book:
  title: "Alerta 1. Caracterización de estudiantes"
  subtitle: "Encuesta de caracterización de estudiantes de primer ingreso - 2025-1"
  author: "Dirección de Analítica Académica – Universidad de Santander"
  date: "2025-05-05"
  reader-mode: true
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - Sesion1.qmd
    - filtro.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: 
      - cosmo
      - brand
    toc: true
    toc-depth: 3
    number-sections: true
    linkcolor: "#046A38"
    fontsize: 1em
    css: style.css
    fig-cap-location: top
    reference-location: margin
    cite-method: citeproc
    biblio-style: apa
    crossref:
      chapters: true
      title-delim: "."
      fig-prefix: "Figura"
      tbl-prefix: "Tabla"
    page-layout: full  # 🔸 Asegura que plotly use todo el ancho sin desbordes

editor: visual